### ISSUE TITLE
Support client-side conversion

### ISSUE THREAD

**Issue by mcnuttandrew** [adrianlee44/ical2json#14]
It would be cool if this library support browser usage. I've tried mocking this up for myself by taking the convert function out of index.js and removing all of the node specific code (eg fs etc), I find that it works like a charm. While this copy-pasta solution works for my use case, it would be particularly cool if this functionality was supported right out of the box.

Thanks for making this nice library!

**Comment by adrianlee44** [comment]
@mcnuttandrew I have split out the node specific code and requiring index.js should now work with browser. There are a few more things I would like to do before making a new minor build.
