### ISSUE TITLE
No file produced on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by Will7838** [adrianlee44/ical2json#16]
Hi there,

When I run the program to convert .ics to .json on my RPI, I get no json file, no error message, the console just starts a new line after a second or two.

If I just type in ical2json, the usage info comes up.

Any ideas what's going on?

Thanks,
Will

**Comment by adrianlee44** [comment]
It needs the ics filename as the first argument.

I'm not sure what's going on here but it might be the ics is invalid. Have you tried to run it through a validator?

**Comment by Will7838** [comment]
Very good point.. I had a unix script to download a file and I think it corrupted it somehow.

Thanks,
Will
