### ISSUE TITLE
Missing declaration file ical2json.d.ts in published NPM package?

### ISSUE THREAD

**Issue by dagilleland** [adrianlee44/ical2json#55]
I'm curious as to why the `build/ical2json.d.ts` isn't part of the published npm package for ical2json?

I realize your primary focus is having this as a stand-alone CLI (which works great, btw), but in my particular TypeScript project, I'm getting error `ts(7016) Could not find a declaration file`. It's probably popping up on my radar in part due to my tsconfig requirements, but with your `package.json` being explicit on the types, I would have thought that the file should be exported as part of the published npm package.

![image](https://github.com/adrianlee44/ical2json/assets/2947017/1d7aa8f5-0c1b-40f6-94c8-002eda90e1ff)

**Comment by adrianlee44** [comment]
This was a miss on my end. Let me look into including the definition and will publish a new version afterwards.
