### ISSUE TITLE
Option to write JSON from converted iCal to different directory?

### ISSUE THREAD

**Issue by jamesmacwhite** [adrianlee44/ical2json#56]
Would there be a way to output the converted JSON to a different directory to where the source iCal file current exists?

**Comment by adrianlee44** [comment]
There isn't one at the moment. I don't see any reason why an additional option can't be added to support writing to a specific file path.

**Comment by jamesmacwhite** [comment]
That would be great. Currently I'm using ical2json in conjunction with fs-jetpack to control the destination of the written file to work around this.
